"""Core contracts used by policy test modules and the harness.

How to add a new policy test module:
1) Implement the four extension functions shown in ``tests/policy_templates/example_policy.py``.
2) Return simple callables for create/modify cases; the framework handles orchestration.
3) Run with ``pytest --policy-template path.to.your_module``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Protocol, runtime_checkable


@dataclass(frozen=True)
class PolicyContext:
    """Execution context passed to policy modules and case callables."""

    project_name: str
    work_dir: str
    stack_name: str
    scope: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ProvisionResult:
    """Base result shape for create/modify operations."""

    ok: bool
    operation: str
    resource_id: str | None = None
    operation_id: str | None = None
    stack_outputs: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    error: str | None = None


@dataclass(frozen=True)
class SuccessResult(ProvisionResult):
    """Operation succeeded."""


@dataclass(frozen=True)
class DeniedResult(ProvisionResult):
    """Operation was denied by policy."""

    denied_by_policy: bool = True


@dataclass(frozen=True)
class NotificationObservation:
    """Observed notification generated by policy action."""

    seen: bool
    operation_id: str
    notification_id: str | None = None
    payload: Mapping[str, Any] | None = None


@dataclass(frozen=True)
class ComplianceObservation:
    """Observed compliance state from the external security system."""

    resource_id: str
    scanned: bool
    compliant: bool | None
    status: str | None = None
    details: Mapping[str, Any] | None = None


@runtime_checkable
class CreateCase(Protocol):
    """Callable that creates a resource and returns a provision result."""

    __name__: str

    def __call__(self, ctx: PolicyContext) -> ProvisionResult:
        ...


@runtime_checkable
class ModifyCase(Protocol):
    """Callable that modifies a resource and returns a provision result."""

    __name__: str

    def __call__(self, ctx: PolicyContext, resource: ProvisionResult) -> ProvisionResult:
        ...
